---
# This playbook contains common tasks in this role

- include: splunk.yml
- include: web.yml
- include: security.yml
- include: deploy_monitored_configs.yml

- name: Finished
  debug: msg="Access your freshly configure splunk instance at https://{{ inventory_hostname }}:8443"
