---
# This playbook install the basic cron jobs required in a server



- name: install clamav cron
  copy: src=etc/cron.daily/clamav dest=/etc/cron.daily/clamav owner=root group=root mode=755 
  tags: 
   - configuration
   - security 

 

